### ISSUE TITLE
Only show media controls on hover

### ISSUE THREAD

**Issue by Liz-chan** [Orrielel/BetterDiscordAddons#11]
Seems pretty self-explanatory; hiding the media controls when you're not hovering over the video like YouTube behaves.

**Comment by Orrielel** [comment]
Good one, been slowly doing the media player after a recent Discord update (they went from Chromium 56 to 69), which completely fucked up the native player controls.
So now I'm just copying the Discord player, but with small alterations.

The hovering should be on by default tbh.

**Comment by Liz-chan** [comment]
So now that it only shows on hover, you can't really tell it's a video to play unless you hover over it. Maybe put a play button overlay when the video isn't playing to indicate it's a video.

Also maybe remove the shadow from the top that shows up whenever you hover over the video.

**Comment by Orrielel** [comment]
Yeah good idea!

The shadow is something from the default Discord style, but haven't really annoyed me. I've had a previous comment on it causing play/pause issues when clicking the video, which I'm aware off, but been slightly lazy about looking into.
Is it that what you're referring to, or just the shadow itself?

**Comment by Liz-chan** [comment]
Oh, I hadn't even noticed that it blocks you from clicking the video, that's annoying. Well that's another reason to remove it. But the main reason that I asked was because aesthetically I think it would look better without a shadow. I think it's there to distinguish the buttons from the video, but maybe you could give all the buttons an outline or a shadow, so you can always see them.

**Comment by Orrielel** [comment]
Damn you're fast.
Yeah, an outline should be feasible.
I'll cook something up throughout the day.

Add me on Orrie#1000 if you want a quicker response. 👍

**Comment by Liz-chan** [comment]
Yeah, I get instant notifications from my email haha.
Happy to hear it, best of luck!
