### ISSUE TITLE
Class change, broke BetterImagePopups

### ISSUE THREAD

**Issue by CompletelyUnbelievable** [Orrielel/BetterDiscordAddons#14]
Change _modal-36zFtW_ to _modal-3c3bKg_, I have not noticed any other changes that cause issues so far. Might be related to #13 but I only started having issues recently.

**Comment by nerdorican** [comment]
it stopped working again yesterday

**Comment by Orrielel** [comment]
Aye, fixed it. https://github.com/Orrielel/BetterDiscordAddons/commit/3aaa7c1e18751c85ff0dfa829b7f5855af09c356
