### ISSUE TITLE
greentexting doesn't always apply

### ISSUE THREAD

**Issue by bootscootboog** [Orrielel/BetterDiscordAddons#16]
Greentexting sometimes only applies to the very first line in a post until the page is reloaded.

**Comment by Orrielel** [comment]
Somewhat very late reply, but will do if I find time at some point in the future.

**Comment by bootscootboog** [comment]
No worries mate, thanks for the reply

**Comment by bootscootboog** [comment]
Recent update has broken this again, not sure why discord keeps messing with the text format
