### ISSUE TITLE
Better Image Popups cutting off the lower part of images

### ISSUE THREAD

**Issue by jacobmix** [Orrielel/BetterDiscordAddons#17]
**Name**
In which plugin or theme does the bug occur:
__Better Image Popups v1.5.3 by Orrie__

**Describe the bug**
The lowest part of the image is getting cut off if "Full Resolution Images" is on.
But i have to have that setting on for the plugin to work, and be able to zoom.
Even with "Load on Click" it will be broken when the image first get's expanded (Popup'd).
When i click on the image i can then zoom, and scroll the image down to see it the cut off part.

**To Reproduce**
When does the bug occur:
Click on an image in a message in Discord to popup the image with the plugin active.

**Expected behavior**
A clear and concise description of what you expected to happen:
For the whole image being shown when first being popup'd.
Then when i click on the image i can zoom, and such.

**Screenshots**
If applicable, add screenshots to help explain your problem:
Before clicking on the image popup image:https://prnt.sc/q188kx | After: https://prnt.sc/q188mb
Without the plugin active: http://prntscr.com/q18an4

**Discord Built (stable, ptb or canary):**
Which built of discord are you using:
Stable "app-0.0.305"

**Additional context**
Image Plugins i use:

> Better Image Popups v1.5.3 by Orrie
> CollapsibleEmbeds v2.1.1 by shtrih
> Direct Media v0.1.0 by samfun123
> ImageGallery v1.6.0 by DevilBro
> ImageToClipboard v0.3.3 by Zerebos
> ResizeX v0.1.2 by Anxeal
> ReverseImageSearch v3.4.8 by DevilBro

Full list of plugins i have installed (Few i have disabled tho):

> 0PluginLibrary.plugin.js
> 1lib_discord_internals.plugin.js
> AutoStartRichPresence.plugin.js
> AvatarIconViewer.plugin.js
> BadgesEverywhere.plugin.js
> BDContextMenu.plugin.js
> BetterEmoteSizes.plugin.js
> BetterImagePopups.plugin.js
> BetterNsfwTag.plugin.js
> BetterReplyer.plugin.js
> BetterSearchPage.plugin.js
> BotsMutualGuilds.plugin.js
> changingBackground.plugin.js
> CharCounter.plugin.js
> CheckAllPluginsButton.plugin.js
> Citador.plugin.js
> clock.plugin.js
> CollapsibleEmbeds.plugin.js
> copyCode.plugin.js
> dateViewer.plugin.js
> DeveloperUtils.plugin.js
> directMedia.plugin.js
> DiscordCakeDay.plugin.js
> discordexperiments.plugin.js
> DiscordLogger.plugin.js
> DoNotTrack.plugin.js
> EmoteBlacklistRedux.plugin.js
> emoteSorter.plugin.js
> FriendNotifications.plugin.js
> full_offline_list.plugin.js
> GuildAndFriendRemovalAlerts.plugin.js
> HorizontalCodeScroll.plugin.js
> ImageGallery.plugin.js
> ImageToClipboard.plugin.js
> KawaiiEmotes.plugin.js
> lazyload_patcher.plugin.js
> LineNumbers.plugin.js
> LineNumbersRedux.plugin.js
> localFileServer.plugin.js
> mediaSupport.plugin.js
> messageTimestamps.plugin.js
> OwnerTag.plugin.js
> PermissionsViewer.plugin.js
> PinPluginsAndThemes.plugin.js
> PluginRepo.plugin.js
> RepoControls.plugin.js
> RepoUtils.plugin.js
> ResizableCSS.plugin.js
> ResizeX.plugin.js
> restartNoMore.plugin.js
> ReverseImageSearch.plugin.js
> SendBDEmotes.plugin.js
> SendButton.plugin.js
> SendLargeMessages.plugin.js
> serverscreenshare.plugin.js
> serverTheme.plugin.js
> ShowHiddenChannels.plugin.js
> ShowImageDetails.plugin.js
> SilentTyping.plugin.js
> SpellCheck.plugin.js
> SteamProfileLink.plugin.js
> suppressmentions.plugin.js
> ThemeCustomizer.plugin.js
> ThemeRepo.plugin.js
> VoiceChatNotifications.plugin.js
>

**Comment by Orrielel** [comment]
Fixed with e3aa9e8ebaf2d479e8f9a27e80697c9b6ede748f

**Comment by jacobmix** [comment]
Thanks. Works now if i disable ImageToClipboard.
ImageToClipboard issue: https://github.com/rauenzi/BetterDiscordAddons/issues/191

**Comment by Orrielel** [comment]
Will take a looksee with that plugin

**Comment by jacobmix** [comment]
New update fixes the line. But now ImageGallery crashes when i switch image.

**Comment by jacobmix** [comment]
Crash on this one:
![image](https://user-images.githubusercontent.com/5995327/69871658-abdc2a00-12b3-11ea-9c6e-100e43a48ec0.png)
It wasn't before. At least i think so.

**Comment by jacobmix** [comment]
Can confirm i seem to crash on every first image of a message or multiple in a row messages with more than one image.
