### ISSUE TITLE
Incompatible with the Image Gallery plugin

### ISSUE THREAD

**Issue by briank6932** [Orrielel/BetterDiscordAddons#18]
I made a corresponding issue post on the [Image Gallery Github](https://github.com/mwittrien/BetterDiscordAddons/issues/325#event-2825534238)

**Comment by Orrielel** [comment]
Might be fixed with e3aa9e8ebaf2d479e8f9a27e80697c9b6ede748f, can you confirm?

**Comment by briank6932** [comment]
It's fixed

**Comment by Orrielel** [comment]
Great
