### ISSUE TITLE
Archive button does not work

### ISSUE THREAD

**Issue by ardittristan** [Orrielel/BetterDiscordAddons#25]
![image](https://user-images.githubusercontent.com/42787508/73317547-c2ace780-4236-11ea-834a-8ff7288225cc.png)

I am getting this error when I press the archive button.

**Comment by Orrielel** [comment]
Does this still occur?

**Comment by ardittristan** [comment]
Yes

**Comment by Orrielel** [comment]
Well that's weird, as I can't reproduce it.
From where are you trying to access it?

**Comment by ardittristan** [comment]
I'm accessing it from the top. Sometimes it appears for a sec and then dissapears again. I do have the mute and help buttons hidden via custom css, but when i comment those out it still doesn't work.

**Comment by Orrielel** [comment]
Could maybe be fixed with c3f24fdcb4784eb7d59b0387eef685381594aeb4, could you test?

**Comment by ardittristan** [comment]
it works great now!

**Comment by Orrielel** [comment]
Very nice!
