### ISSUE TITLE
[BUG] BetterImagePopups zoomed image position

### ISSUE THREAD

**Issue by Trixlight** [Orrielel/BetterDiscordAddons#26]
Currently, if you try to zoom a small image, this will happen:
![2020-02-21_20-53-46](https://user-images.githubusercontent.com/33410668/75049742-80e92700-54ec-11ea-8001-47e742473ae4.gif)

Reset discord default styles by adding
```
flex: unset;
height: unset;
```
to `.bip-container .scrollerWrap-2lJEkd`
not sure if you need to reset `min-height` & `min-width` too

Also, don't use 
```
display: flex;
align-items: self-start;
```
for `.bip-container .bip-scroller` in your code.

This should work, unless I made a mistake.
![2020-02-21_21-10-45](https://user-images.githubusercontent.com/33410668/75050865-a840f380-54ee-11ea-9828-228c7a8c79c7.gif)

**Comment by Orrielel** [comment]
Yeah, it's been kinda neglected after multiple Discord updates.
Maybe I'll fix it, maybe not, can't promise.
