### ISSUE TITLE
[BUG] BetterImagePopups plugin breaks "Delete Message" popup

### ISSUE THREAD

**Issue by Trixlight** [Orrielel/BetterDiscordAddons#27]
It shouldn't work here at all.
![2020-02-21_21-24-04](https://user-images.githubusercontent.com/33410668/75051975-a415d580-54f0-11ea-9df7-f7c8bd5bb55d.gif)
With plugin turned off
![Discord_2020-02-21_21-30-11](https://user-images.githubusercontent.com/33410668/75052415-649bb900-54f1-11ea-96e6-fcd476202041.png)

**Comment by voidn** [comment]
A potential fix for this until it gets properly addressed would be to just manually change the container a bit.

`.da-systemPad {max-width: 100%; max-height: 100%}
.da-systemPad .da-anchor img {max-height: calc(60vh - 220px)}`

**Comment by Orrielel** [comment]
Yeah, it's been kinda neglected after multiple Discord updates.
Maybe I'll fix it, maybe not, can't promise.
