### ISSUE TITLE
Twitch Stream Panel plugin breaks often

### ISSUE THREAD

**Issue by janez33** [Orrielel/BetterDiscordAddons#7]
I figured out that switching between direct messages tab and server tab breaks Twitch Stream panel plugin. Can you please fix this issue?

**Comment by Orrielel** [comment]
Aye, I've neglected the Twitch Stream Panel for some time and it really deserve a rewrite.
If I ever get my spirit raised, I'll do that.

In the meantime, I think the changes I'm gonna push should suffice for it to load better. (Or so I hope)
