### ISSUE TITLE
Better Image Popups screws with the change log

### ISSUE THREAD

**Issue by CompletelyUnbelievable** [Orrielel/BetterDiscordAddons#8]
I made a post about this issue in the BD1 guild the other day. I don't know if there is any other underlying issue casing it other than Better Image Popups.

Ignore the fact I am using a theme in this image, still occurs without a theme.
![image](https://user-images.githubusercontent.com/39345185/46737137-9b03cb80-cc4f-11e8-9a3c-e30203be6bb7.png)

**Comment by Orrielel** [comment]
Seems like it hooks into media it shouldn't. I'll look into it later today.

**Comment by Orrielel** [comment]
Fixed in https://github.com/Orrielel/BetterDiscordAddons/commit/57448ced112c323507fea6bbefd8a444f5d03b46
