### ISSUE TITLE
[Suggestion] Add changelogs to plugins

### ISSUE THREAD

**Issue by snappyapple632** [Orrielel/BetterDiscordAddons#9]
I received an update to the Twitch stream plugin, but I have no knowledge of what has been changed/updated.

**Comment by Orrielel** [comment]
Tbh too much work for arbitrary gain.
I'm sure some are interested in what's changed, but usually they're minor fixes or not relevant to the user experience.
I can start writing in the commits here what I've changed, but I can't be arsed to write a function for it.
Sorry fam.
